name: Dotty CI

on: push

env:
  DOTTY_CI_RUN: true

jobs:
  nightly_documentation:
    runs-on: ubuntu-latest
    container: lampepfl/dotty:2020-04-24
    env:
      NIGHTLYBUILD: yes

    steps:
      - name: Checkout cleanup script
        uses: actions/checkout@v2

      - name: Cleanup
        run: .github/workflows/cleanup.sh

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Generate Website
        run: |
          ./project/scripts/genDocs -doc-snapshot

      - name: Deploy Website
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages-test
          FOLDER: docs/_site
          REPOSITORY_NAME: lampepfl/dotty-website
