name: Dotty CI

on: push

env:
  DOTTY_CI_RUN: true

jobs:
  nightly_documentation:
    runs-on: ubuntu-latest
    container: lampepfl/dotty:2020-04-24
    env:
      NIGHTLYBUILD: yes

    steps:
      - name: Checkout cleanup script
        uses: actions/checkout@v2

      - name: Cleanup
        run: .github/workflows/cleanup.sh

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Generate Website
        run: |
          ./project/scripts/genDocs -doc-snapshot

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT_TOKEN }}
          publish_dir: docs/_site
          external_repository: anatoliykmetyuk/dummy-docs
          publish_branch: master
