name: CI Failure Watchdog

on: push

jobs:
  create_issue:
    runs-on: self-hosted
    container: akmetiuk/dotty:2020-02-12

    if: github.event.check_suite.head_branch == 'ci-release-test' &&
        github.event.check_suite.status == 'completed' &&
        github.event.check_suite.conclusion == 'cancelled'

    steps:
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/workflows/ci_failure_watchdog_template.md

